/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerSession {
  'matchPercentage' : number,
  'timestamp' : Time,
  'careerPathName' : string,
  'skills' : Array<string>,
}
export interface InterviewSession {
  'strengths' : Array<string>,
  'improvements' : Array<string>,
  'feedback' : string,
  'score' : bigint,
  'interviewType' : string,
  'timestamp' : Time,
}
export interface LeaderboardEntry {
  'username' : string,
  'badges' : Array<string>,
  'rank' : bigint,
  'totalScore' : bigint,
  'sessionsCount' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'avatarUrl' : string,
  'quizAnswers' : Array<string>,
  'currentSituation' : string,
}
export interface _SERVICE {
  'getCareerSessions' : ActorMethod<[], Array<CareerSession>>,
  'getInterviewSessions' : ActorMethod<[], Array<InterviewSession>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getUserProfile' : ActorMethod<[], UserProfile>,
  'saveCareerSession' : ActorMethod<[string, number, Array<string>], undefined>,
  'saveInterviewSession' : ActorMethod<
    [string, bigint, string, Array<string>, Array<string>],
    undefined
  >,
  'updateProfile' : ActorMethod<
    [string, string, string, string, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];