/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CareerSession = IDL.Record({
  'matchPercentage' : IDL.Nat8,
  'timestamp' : Time,
  'careerPathName' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
});
export const InterviewSession = IDL.Record({
  'strengths' : IDL.Vec(IDL.Text),
  'improvements' : IDL.Vec(IDL.Text),
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'interviewType' : IDL.Text,
  'timestamp' : Time,
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'badges' : IDL.Vec(IDL.Text),
  'rank' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'sessionsCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'quizAnswers' : IDL.Vec(IDL.Text),
  'currentSituation' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCareerSessions' : IDL.Func([], [IDL.Vec(CareerSession)], ['query']),
  'getInterviewSessions' : IDL.Func([], [IDL.Vec(InterviewSession)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'saveCareerSession' : IDL.Func(
      [IDL.Text, IDL.Nat8, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'saveInterviewSession' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CareerSession = IDL.Record({
    'matchPercentage' : IDL.Nat8,
    'timestamp' : Time,
    'careerPathName' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
  });
  const InterviewSession = IDL.Record({
    'strengths' : IDL.Vec(IDL.Text),
    'improvements' : IDL.Vec(IDL.Text),
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'interviewType' : IDL.Text,
    'timestamp' : Time,
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'badges' : IDL.Vec(IDL.Text),
    'rank' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'sessionsCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'quizAnswers' : IDL.Vec(IDL.Text),
    'currentSituation' : IDL.Text,
  });
  
  return IDL.Service({
    'getCareerSessions' : IDL.Func([], [IDL.Vec(CareerSession)], ['query']),
    'getInterviewSessions' : IDL.Func(
        [],
        [IDL.Vec(InterviewSession)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'saveCareerSession' : IDL.Func(
        [IDL.Text, IDL.Nat8, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'saveInterviewSession' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };